---
name: Bump Version Tag

on:
  push:
    branches:
      - main
    paths:
      - "**/*"
      - "!**/*.json"
      - "!**/*.json5"
      - "!**/*.md"
      - "!.github/**"
      - "!.gitignore"
      - "!.pre-commit-config.yaml"
  workflow_dispatch:

jobs:
  tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Extract major tag
        id: extract-major
        run: >-
          echo major_tag="$(echo ${{ steps.bump-version.outputs.new_tag }} | cut
          -d'.' -f1)" >> "$GITHUB_OUTPUT"

      # this is done manually as need a non-annotated tag
      # TODO: replace with https://github.com/actions/publish-action
      - name: Update major tag
        run: |-
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag --force ${{ steps.extract-major.outputs.major_tag }} \
          ${{ steps.bump-version.outputs.new_tag }}
          git push origin ${{ steps.extract-major.outputs.major_tag }} --force
